<template>
<div class="create-view">
  <div class="create-container">
    <h1>Create a New Discussion</h1>
    <form @submit.prevent="createDiscussion" class="form">
      <input
        type="text"
        v-model="title"
        placeholder="Discussion Title"
        required
      />
      <select v-model="category" required>
        <option value="" disabled>Select a Category</option>
        <option v-for="cat in categories" :key="cat" :value="cat">
          {{ cat }}
        </option>
        <option value="custom">Create New Category</option>
      </select>
      <input
        v-if="category === 'custom'"
        type="text"
        v-model="customCategory"
        placeholder="Enter New Category"
        required
      />
      <textarea
        v-model="content"
        placeholder="Discussion Content"
        rows="5"
        required
      ></textarea>
      <button type="submit" class="btn">Create Discussion</button>
    </form>
  </div>
</div>
</template>

<script setup>
// a discussion is an object that contains the following properties:
/*
    - id: string (auto generated by firebase)
    - userId: string (the id of the user who created the discussion)
    - Title: string (the title of the discussion)
    - category: string (the category of the discussion chosen from the list or created by the user)
    - content: string (the content of the discussion)
    - date: timestamp (the date of the discussion)
    - comments: array of strings (each string is the id of the comment)
    - likes: array of strings (each string is the id of the user who liked the discussion)
    - signals: array of objects (each object contains information about the signal type and the user who reported it)
        Example:
        signals: [

            { userId: "user1", type: "NSFW" },
            { userId: "user2", type: "Abusive" }
        ]
*/

import { ref } from "vue";
import { db, auth } from "@/Firebase/Config";
import { useRouter } from "vue-router";

const router = useRouter();
const title = ref("");
const category = ref("");
const customCategory = ref("");
const content = ref("");
const categories = ref(["General", "Technology", "Health", "Education"]); // Example categories

async function createDiscussion() {
  try {
    // just in case
    const user = auth.currentUser;
    if (!user) {
      alert("You must be logged in to create a discussion.");
      return;
    }

    const discussionData = {
      userId: user.uid,
      title: title.value,
      category:
        category.value === "custom" ? customCategory.value : category.value,
      content: content.value,
      date: new Date(),
      comments: [],
      likes: [],
      signals: [],
    };

    // Add the discussion to the Firestore database
    await db.collection("discussions").add(discussionData);

    alert("Discussion created successfully!");
    // Reset the form
    title.value = "";
    category.value = "";
    customCategory.value = "";
    content.value = "";

    // reroute to the home page
    router.push("/");
  } catch (error) {
    console.error("Error creating discussion:", error);
    alert("An error occurred while creating the discussion. Please try again.");
  }
}
</script>

<style scoped>
/* Import Google Font */
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap");

.create-view {
  background: linear-gradient(135deg, rgb(242, 239, 231), #48a6a7); /* Gradient background */
  animation: gradientAnimation 10s ease infinite;
  width: 100%;
  height: Calc(100vh - 100px);
  display: flex;
  align-items: center;
  justify-content: center;
}
/* General container styling */
.create-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  background: #F2EFE7; /* Gradient background for the container */
  background-size: 400% 400%;
  border-radius: 15px;
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2);
  width: 100%;
  height: auto;
  max-width: 600px;
  margin: 2rem auto;
  font-family: "Poppins", sans-serif;
}

h1 {
  color: #333;
  margin-bottom: 1rem;
  font-size: 1.8rem;
  font-weight: 600;
  text-align: center;
}

.form {
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.form input,
.form textarea {
  width: calc(100% - 1.6rem); /* Subtract 0.8rem from the width */
  border: 1px solid #ccc;
  padding: 0.8rem;
  border-radius: 5px;
  font-size: 1rem;
  font-family: "Poppins", sans-serif;
}

.form select{
  width: 100%;
  padding: 0.8rem;
  border: 1px solid #ccc;
  border-radius: 5px;
  font-size: 1rem;
  font-family: "Poppins", sans-serif;
}

.form textarea {
  resize: none;
}

.form input:focus,
.form select:focus,
.form textarea:focus {
  outline: none;
  border-color: #006a71;
  box-shadow: 0 0 5px rgba(0, 106, 113, 0.5);
}

.btn {
  padding: 0.8rem;
  background: linear-gradient(135deg, #85DE7C, #48a6a7); /* Gradient background for the button */
  animation: gradientAnimation 10s ease infinite;
  color: #fff;
  border: none;
  border-radius: 5px;
  font-size: 1rem;
  font-family: "Poppins", sans-serif;
  cursor: pointer;
  transition: background 0.3s ease, transform 0.2s ease;
}

.btn:hover {
  transform: scale(1.05);
}

/* Gradient animation */
@keyframes gradientAnimation {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}
</style>
