/*
  - id: string (auto generated by firebase)
  - userId: string (the id of the user who created the discussion)
  - title: string (the title of the discussion)
  - category: array (the category of the discussion chosen from the list or created by the user)
  - subcategory: array (determined according to the category)
  - content: string (the content of the discussion)
  - date: timestamp (the date of the discussion)
  - comments: array of strings (each string is the id of the comment)
  - likes: array of strings (each string is the id of the user who liked the discussion)
  - signals: array of objects (each object contains information about the signal type and the user who reported it)
      Example:
      signals: [
          { userId: "user1", type: "NSFW" },
          { userId: "user2", type: "Abusive" }
      ]
*/



<template>
    <div>
    <Card v-if="currentDiscussion" :discussion="currentDiscussion" :key="Cardkey" @remount="remountCard"/>
    <div v-else class="loading">
        <p>Loading...</p>
    </div>
    </div>

</template>


<script setup>


import { useRoute } from 'vue-router';
import { ref, onMounted} from 'vue';
import { db } from '@/Firebase/Config'; // Import your Firebase configuration
import Card from '@/components/Card.vue';



const currentDiscussion = ref(null);
const route = useRoute();
const discussionId = route.params.id; // Get the discussion ID from the route parameters
const isReply = route.params.isReply; // Get the isReply parameter from the route
const Cardkey = ref(0);


//Variables to print


 





// Fetch Discussion Data
const fetchDiscussion = async () => {
    if (!isReply){
        const docRef = db.collection('discussions').doc(discussionId);
        const doc = await docRef.get();
        if (doc.exists) {
            currentDiscussion.value = { id: doc.id, ...doc.data() };
            console.log("Discussion data:", currentDiscussion.value);
            
            
        } else {
            console.log("No such document!");
        }
    } else {
        const docRef = db.collection('replies').doc(discussionId);
        const doc = await docRef.get();
        if (doc.exists) {
            currentDiscussion.value = { id: doc.id, ...doc.data() };
        } else {
            console.log("No such document!");
        }
    }
    
};



const remountCard = () => {
    Cardkey.value += 1; // Increment the key to force re-rendering of the Card component
};



onMounted(async () => {
    await fetchDiscussion();
    console.log(currentDiscussion.value);
});


</script>

