<template>
  <div class="card-container">
    <!-- Card Header with User Information -->
    <div class="card-header" >
      <div class="user-icon" @click.stop="goToUser">
        <img :src="userIcon" alt="User Icon" />
        <p>{{ userName }}</p>
      </div>
      <div class="options-icon" v-if="isCurrentUser">
        <i class="fas fa-ellipsis-h"></i>
      </div>
    </div>

    <!-- Card Body with the Discussion Content -->
    <div class="card-body" @click="goToDiscussion">
      <h2 class="discussion-title">{{ discussion.title }}</h2>
      <p class="discussion-description">{{ discussion.content }}</p>
    </div>

    <!-- Card Footer -->
    <hr style="width: 100%; border: 1px solid #ccc; margin: 0.5rem 0;" />
    <div class="card-footer">
      <div class="action" @click.stop="toggleLike">
        <i :class="isLiked ? 'fas fa-heart liked' : 'far fa-heart'"></i>
        <span>{{ discussion.likes.length }}</span>
      </div>
      <div class="action" @click.stop="goToDiscussion">
        <i class="far fa-comment"></i>
        <span>{{ discussion.comments.length }}</span>
      </div>
      <div class="action" @click.stop="toggleSave">
        <i :class="isSaved ? 'fas fa-bookmark saved' : 'far fa-bookmark'"></i>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, defineProps, onMounted, computed } from "vue";
import { useRouter } from "vue-router";
import { db, auth } from "@/Firebase/Config";

const props = defineProps({
  discussion: {
    type: Object,
    required: true,
  },
});

// discussion is passed with :
/*
  - id: string (auto generated by firebase)
  - userId: string (the id of the user who created the discussion)
  - Title: string (the title of the discussion)
  - category: string (the category of the discussion chosen from the list or created by the user)
  - content: string (the content of the discussion)
  - date: timestamp (the date of the discussion)
  - comments: array of strings (each string is the id of the comment)
  - likes: array of strings (each string is the id of the user who liked the discussion)
  - signals: array of objects (each object contains information about the signal type and the user who reported it)
      Example:
      signals: [
          { userId: "user1", type: "NSFW" },
          { userId: "user2", type: "Abusive" }
      ]
*/
// the post can also be saved by the user => need to check if it is in the user's saved

// Use router to navigate to the discussion detail page
const router = useRouter();
const userIcon = ref("https://cdn-icons-png.flaticon.com/512/149/149071.png");
const userName = ref("");
const isLiked = ref(false);
const isSaved = ref(false);
const isCurrentUser = computed(
  () => auth.currentUser?.uid === props.discussion.userId
);

const getTheUserIconandName = async () => {
  const doc = await db.collection("users").doc(props.discussion.userId).get();
  if (doc.exists) {
    const userData = doc.data();
    userIcon.value =
      userData.imageURL ||
      "https://cdn-icons-png.flaticon.com/512/149/149071.png"; // Default icon if no imageURL
    userName.value = userData.username || "Guest"; // Default name if no name

    // check the saves
    isSaved.value =
      userData.saved && userData.saved.includes(props.discussion.id);
  }
};

const toggleLike = async () => {
  const userId = auth.currentUser?.uid;
  if (!userId) return alert("You must be logged in to like posts.");

  const likes = props.discussion.likes || [];
  if (likes.includes(userId)) {
    // Unlike the post
    await db
      .collection("discussions")
      .doc(props.discussion.id)
      .update({
        likes: likes.filter((id) => id !== userId),
      });
    isLiked.value = false;
    //update the props.discussion.likes
    props.discussion.likes = likes.filter((id) => id !== userId);
  } else {
    // Like the post
    await db
      .collection("discussions")
      .doc(props.discussion.id)
      .update({
        likes: [...likes, userId],
      });
    isLiked.value = true;
    //update the props.discussion.likes
    props.discussion.likes = [...likes, userId];
  }

};

const toggleSave = async () => {
  const userId = auth.currentUser?.uid;
  if (!userId) return alert("You must be logged in to save posts.");

  const userDoc = await db.collection("users").doc(userId).get();
  const savedPosts = userDoc.data()?.savedPosts || [];
  if (savedPosts.includes(props.discussion.id)) {
    // Unsave the post
    await db
      .collection("users")
      .doc(userId)
      .update({
        savedPosts: savedPosts.filter((id) => id !== props.discussion.id),
      });
    isSaved.value = false;
  } else {
    // Save the post
    await db
      .collection("users")
      .doc(userId)
      .update({
        savedPosts: [...savedPosts, props.discussion.id],
      });
    isSaved.value = true;
  }
};

const goToDiscussion = () => {
  router.push({ name: "discussion", params: { id: props.discussion.id } });
};

const goToUser = () => {
  router.push({ name: "user", params: { id: props.discussion.userId } });
};

onMounted(async () => {
  await getTheUserIconandName();

  const userId = auth.currentUser?.uid;
  if (userId) {
    isLiked.value = props.discussion.likes.includes(userId);

    const userDoc = await db.collection("users").doc(userId).get();
    const savedPosts = userDoc.data()?.savedPosts || [];
    isSaved.value = savedPosts.includes(props.discussion.id);
  }
});
</script>

<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap");

.card-container {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  padding: 1rem;
  background: rgba(242, 239, 231, 0.69);
  border-radius: 8px;
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.2);
  width: 800px;
  margin: 0 auto;
  font-family: "Poppins", sans-serif;
  cursor: pointer;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.card-header .user-icon {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.card-header .user-icon img {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  border: 2px solid #006a71;
}

.card-header .user-icon p {
  margin: 0;
  color: black;
  font-weight: 600;
}

.options-icon {
  font-size: 1.2rem;
  color: #333;
  cursor: pointer;
}

.card-body {
  display: flex;
  flex-direction: column;
  align-items: center;
  color: #333;
  padding-top: 0.5rem;
}

.card-body .discussion-title {
  font-size: 1.5rem;
  font-weight: 600;
  color: #006a71;
}

.card-body .discussion-description {
  font-size: 1rem;
  color: #333;
}

.card-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 1rem;
}

.action {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  cursor: pointer;
}

.action i {
  font-size: 1.2rem;
  color: #333;
}

.action i.liked {
  color: #e63946;
}

.action i.saved {
  color: #006a71;
}

.action span {
  font-size: 1rem;
  color: #333;
}
</style>
